# Generated by Django 5.2.3 on 2025-06-18 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0004_user1_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DiaryProduct',
            fields=[
                ('newproduct_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DjangoProject.newproduct')),
                ('expiry_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diaryproduct',
            },
            bases=('DjangoProject.newproduct',),
        ),
    ]
