# Generated by Django 5.2.3 on 2025-06-22 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0006_userflipkart_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflipkart',
            name='default_shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='user_info', to='DjangoProject.shippingaddress'),
        ),
    ]
