# Generated by Django 5.2.3 on 2025-06-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0007_userflipkart_default_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProductJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'newproduct_json',
            },
        ),
    ]
